// sidebars.js

module.exports = {
  docs: [
    "intro",

    {
      type: "category",
      label: "Foundation",
      link: {
        type: "generated-index",
        title: "Foundation",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "foundation",
        },
      ],
    },

    {
      type: "category",
      label: "Products",
      link: {
        type: "generated-index",
        title: "Products",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "products",
        },
      ],
    },

    {
      type: "category",
      label: "Platform",
      link: {
        type: "generated-index",
        title: "Platform",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "platform",
        },
      ],
    },

    {
      type: "category",
      label: "Deployment",
      link: {
        type: "generated-index",
        title: "Deployment",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "deployment",
        },
      ],
    },

    {
      type: "category",
      label: "Reference",
      link: {
        type: "generated-index",
        title: "Reference",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "reference",
        },
      ],
    },
  ],
};
