/**
 * Atlas Runtime Governance Documentation
 */

module.exports = {
  docs: [
    "intro",

    {
      type: "category",
      label: "基础理论",
      link: {
        type: "generated-index",
        title: "基础理论",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "foundation",
        },
      ],
    },

    {
      type: "category",
      label: "产品体系",
      link: {
        type: "generated-index",
        title: "产品体系",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "products",
        },
      ],
    },

    {
      type: "category",
      label: "平台架构",
      link: {
        type: "generated-index",
        title: "平台架构",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "platform",
        },
      ],
    },

    {
      type: "category",
      label: "部署指南",
      link: {
        type: "generated-index",
        title: "部署指南",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "deployment",
        },
      ],
    },

    {
      type: "category",
      label: "参考资料",
      link: {
        type: "generated-index",
        title: "参考资料",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "reference",
        },
      ],
    },
  ],
};
